### ISSUE TITLE
Be able to navigate to entries from different dictionaries more easily

### ISSUE THREAD

**Issue by vvasuki** [sanskrit-coders/nakshatra-app#5]
When I look for a word, I get entries from multiple dictionaries. Sometimes one wants to quickly scroll to the particular entry one's interested - eg. amarakosha for hari (as one can do in other apps like goldendict, ebdic, ...). Currently one cannot do this.

**Comment by damooo** [comment]
swipe from right edge of the screen!!
![screenshot_1526310450](https://user-images.githubusercontent.com/11977457/40603231-ff558402-6278-11e8-9af8-81f6e7a83a0a.png)

**Comment by vvasuki** [comment]
Oh nice!
